apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  ports:
  - port: 8000 # the port that this service should serve on
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx
